# Generated by Django 5.0.6 on 2026-03-09 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('fruit_basket', 'Fruit Basket'), ('mix_basket', 'Fruit & Vegetable Basket'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable')], max_length=50)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('items', models.JSONField(blank=True, default=list, null=True)),
                ('vitamins', models.JSONField(blank=True, default=list, null=True)),
                ('desc_1', models.TextField(blank=True, null=True)),
                ('desc_2', models.TextField(blank=True, null=True)),
                ('image_1', models.CharField(max_length=500)),
                ('image_2', models.CharField(max_length=500)),
                ('image_3', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Product',
                'ordering': ['-created_at'],
            },
        ),
    ]
