# Generated by Django 5.0.6 on 2026-05-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_image_2_alter_product_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sales_type',
            field=models.CharField(choices=[('by_piece', 'Sold by the piece'), ('by_kilogram', 'Sold by the kilogram')], default='by_kilogram', max_length=50),
        ),
    ]
