# Generated by Django 5.0.6 on 2026-05-14 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_sales_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='product.product')),
            ],
            options={
                'db_table': 'ProductPackage',
                'ordering': ['weight_kg'],
            },
        ),
        migrations.AddConstraint(
            model_name='productpackage',
            constraint=models.UniqueConstraint(fields=('product', 'size'), name='unique_package_size_per_product'),
        ),
    ]
